### ISSUE TITLE
RBASIC(result)->klass = ... breaks on Ruby2.2

### ISSUE THREAD

**Issue by suther** [vteams/open-source-billing#21]
Here is the error-message:

> /usr/bin/ruby2.2 -r ./siteconf20150525-22431-1hkf7n3.rb extconf.rb
creating Makefile

>make "DESTDIR=" clean

>make "DESTDIR="
compiling buffer.c
compiling houdini_uri_u.c
compiling escape_utils.c
In file included from /usr/include/ruby-2.2.0/ruby.h:33:0,
                 from escape_utils.c:6:
escape_utils.c: In function ‘rb_eu_escape_html_as_html_safe’:
/usr/include/ruby-2.2.0/ruby/ruby.h:1082:30: error: assignment of read-only member ‘klass’
 #define RBASIC(obj)  (R_CAST(RBasic)(obj))
                              ^
/usr/include/ruby-2.2.0/ruby/ruby.h:1081:30: note: in definition of macro ‘R_CAST’
 #define R_CAST(st)   (struct st*)
                              ^
escape_utils.c:126:2: note: in expansion of macro ‘RBASIC’
  RBASIC(result)->klass = rb_html_safe_string_class;
  ^
make: *** [escape_utils.o] Fehler 1

>make failed, exit code 2

What can I do to fix this?

**Comment by shahzad-nxb** [comment]
This issue is due to compatibility issue of 'escape_utils' gem with ruby 2.1.0 or greater versions. We recommend using ruby 2.0.0 for OSB installation. Please install and use ruby 2.0.0 on your system and then install bundler gems using bundle install command.

**Comment by raomin** [comment]
Hi,
I had the same issue with the 2.2.0. I got the install to work with ruby 2.2.2 and with escape_utils (1.0.0)
